---
title: "02_AA_Analysis"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
```

```{r AA Data}
AA <- read_csv("~/R/C313_JCWSoilAnalysis/Data/AA_Data_Tidy.csv") %>%
  mutate(metal = "Cr", RSD = as.numeric(X.RSD))
View(AA)
```

```{r Defining lists}
sample_sites <- unique(filter(AA, Site!="MB", Site!="")$Site)
#excluding method blank and quality control from the list of sites
metals_analyzed <- unique(AA$metal)

#Preview the lists to check for potential issues
sample_sites
metals_analyzed
```

```{r Calibration}
#For loop
AA_cal <- NULL
for (unique_metal in metals_analyzed){
  cal <- AA %>%
    filter(Type!= "Sample") %>%
    filter(metal == unique_metal)%>%
    select(Concentration,RSD,CPS=Mean.Abs.)
  
#Perform a weighted linear regression, account for uncertainty in the CPS by weighting the regression with the RSD readings  
  w <- 1/(cal$CPS*cal$RSD)^2
  model <- lm(cal$CPS ~ cal$Concentration, weights = w)
  
#Pulling info from model to be stored in a tidy calibration data set  
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
 
#Plot calibration curve   
  plot(cal$CPS ~ cal$Concentration,
       xlab= paste("Concentration of ", unique_metal, "(ppm)"), #units from the standard solution prepared at OHSU (µg/L)
       ylab= "Absorbance")+
       abline(model, col="red")+
       title(paste("Calibration for", unique_metal))
  equation <- tibble(metal= unique_metal, slope, slope_std, intercept, intercept_std)
  AA_cal <- rbind(AA_cal, equation)
}

AA_cal
#Clearing the envrironment
remove(equation, cal, slope, slope_std, intercept, intercept_std, w, model, unique_metal)
```

```{r Creating a function for sample analysis}
#inputs: unique_site (as a character, ex. "A")
#outputs: concentration vector

sample_analysis <- function(unique_Site){
  concentration_data <- NULL
  for (unique_metal in metals_analyzed){
    sample <- filter(AA, metal == unique_metal, Site == unique_Site)
    data <- NULL
    
    for(ID in sample$Sample.Key){
      sample_data <- filter(sample, Sample.Key == ID)
      cal <- filter(AA_cal, metal == unique_metal)
      
      #sample analysis
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$Mean.Abs.
      
      b_e <- cal$intercept_std
      m_e <- cal$slope_std
      
      x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
      
      rsd <- ((sample_data$RSD/100)*sample_data$Mean.Abs.)
      mean.abs. <- sample_data$Mean.Abs.
      
      #error propagation
      e_yb <- sqrt((rsd)^2 + (b_e)^2) 
      #error in the y-b from the calibration
      yb <- mean.abs.-b
      e_x <- x*sqrt((e_yb/yb)^2 + (m_e/m)^2)
      #error in x from the calibration
      
      data <- rbind(data, data_frame(Sample.Key = ID, x, e_x))
      if(unique_Site!= "MB"){
        concentration_data <- data_frame(Sample.Key = sample_data$Sample.Key,
                                         Analyst = sample_data$Analyst,
                                         metal = unique_metal,
                                         Site = unique_Site,
                                         conc_dil = x,
                                         conc_dil_error = e_x)%>%
          rbind(concentration_data)
      }
      if (unique_Site=="MB"){
        x <- mean(data$x)
        e_x <- sd(data$x)
        concentration_data <- data_frame(metal = unique_metal,
                                         Site = unique_Site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
    }
    return(concentration_data)
  }
}
```

```{r Creating a function for different soil sample sites}
#inputs: a function
#outputs: a data frame withe the function outputs from each site
run_sites <- function(Function){
  value <- NULL
  for(sites in sample_sites){
    site_value <- Function(sites)
    value <- rbind(site_value, value)
  }
  return(value)
}
```

```{r Analyze method blanks}
MB <- sample_analysis("MB") #(µg/kg)
uncor_sample <- run_sites(sample_analysis) #values do not account for dilutions (µg/kg)

MB
uncor_sample
```

```{r Corrections and error propagation}
sample_data_mb <- NULL

for (unique_metal in metals_analyzed){
  MB_metal <- filter(MB, metal==unique_metal)
  sample_metal <- filter(uncor_sample, metal==unique_metal)
  conc_dil_blanked <- sample_metal$conc_dil - mean(MB_metal$conc_dil)
  
  #Error propagation: subtraction of MB
  conc_dil_blanked_error <- sqrt((sample_metal$conc_dil_error)^2 + (sd(MB_metal$conc_dil))^2)
  
  sample_data_mb <- sample_metal %>%
    mutate(conc_dil_blanked, conc_dil_blanked_error) %>%
    rbind(sample_data_mb)
}

sample_data_mb
```

```{r Dilution factors and measurement errors}
#error propagation
vol_e <- 1
mass_e <- 0.001

sample_data <- merge(AA, sample_data_mb) %>% #This adds in important details such as soil mass
  unique()%>%
  mutate(conc_blanked= conc_dil_blanked*(Total.Volume/1000)/(Mass.of.Soil/1000),
                                                             conc_blanked_error = conc_blanked*
      sqrt((conc_dil_blanked_error/conc_dil_blanked)^2+
             (mass_e/Mass.of.Soil)^2 +
             (vol_e/Total.Volume)^2),
      conc_unblanked = conc_dil*(Total.Volume/1000)/(Mass.of.Soil/1000),
      conc_unblanked_error = conc_unblanked*
        sqrt((conc_dil_error/conc_dil)^2 +
               (mass_e/Mass.of.Soil)^2 +
               (vol_e/Total.Volume)^2)) %>%
select(-Concentration, #removing unnecessary columns
       -Type,
       -Mass.of.Soil,
       -Total.Volume,
       -Mean.Abs.,
       -RSD,
       -X.RSD,
       -X1,
       -conc_dil_blanked,
       -conc_dil_blanked_error,
       -conc_dil,
       -conc_dil_error)

sample_data
```

```{r, warning= FALSE, Clean the Environment}
rm(list = ls()[!(ls() %in% c("AA", "sample_data", "ICPMS", "sample_data_I"))])
```
