---
title: "JCW"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
```

1) Importing the Data
```{r, warning=FALSE, message=TRUE}
#Import ICPMS data -> find path by right clicking on data file (already uploaded in R and selecting "import dataset")
ICPMS_imported <- read.csv("~/R/C313_JCWSoilAnalysis/Data/ICPMS_Data.csv", skip=1, na="N/A") 

#Import ICPMS data -> find path by right clicking on data file (already uploaded in R and selecting "import dataset")
sample_key <- read.csv("~/R/C313_JCWSoilAnalysis/Data/Sample_Key.csv", skip=0)

#Preview Data
ICPMS_imported
sample_key
```

#Data Tidying

2) Tidying the RSD Data
```{r Tidying RSD Data, warning=FALSE, message=FALSE}
RSD_data<-ICPMS_imported %>%
  #first the RSD columns are selected
  #and renamed with the appropriate metal isotope
  select(Cr52 = CPS.RSD,
         Cr53 = CPS.RSD.1,
         As75 = CPS.RSD.2,
         Cd111 = CPS.RSD.3,
         Cd114 = CPS.RSD.4,
         Pb208 = CPS.RSD.5,
         Ge_RSD = CPS.RSD.7,
         Sample.Key)%>%
  #The sample key is also selected for later use in verifying
  #that the RSD data is properly matching the CPS data
  #then the newly renamed RSD columns are gathered together
  #a column is created to indicate which metal corresponds to which RSD
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "RSD")

#Previewing the RSD Data
RSD_data
```

3) Tidying the CPS Data
```{r Tidying CPS Data, warning=FALSE, message=FALSE}
ICPMS_tidy<-ICPMS_imported %>%
  #first the CPS columns are selected
  #and renamed with the appropriate metal isotope
  select(Cr52 = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge_RSD = CPS.7,
         Sample.Key)%>%
  #The sample key is also selected for later use in verifying
  #that the CPS data is properly matching the RSD data
  #then the newly renamed CPS columns are gathered together
  #a column is created to indicate which metal corresponds to which CPS
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "CPS")

#Previewing the CPS Data
ICPMS_tidy
```

4) Tidying the CPS Data and Correcting for ISTD
```{r CPS ICPMS Tidying}
#Tidying the CPS Data for ICPMS and combining back in the RSD Data
ICPMS_tidy <- ICPMS_imported %>%
  select(Cr = CPS,
         Cr53 = CPS.1,
         As75 = CPS.2,
         Cd111 = CPS.3,
         Cd114 = CPS.4,
         Pb208 = CPS.5,
         Ge72 = CPS.7,
         Sample.Key)%>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to = "CPS")%>%
  #mutating in the RSD Data
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS=CPS/Ge72)%>% #ISTD Correction
  select(-Ge72)

#Confirming that the RSD data properly matches the CPS data
#Should output TRUE if the data is properly matching
all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)

#Previewing the ICPMS Data
ICPMS_tidy
```

5) Merging the Sample Key
```{r merging sample key}
#Merging together the ICPMS Data and the Sample Key
ICPMS_merged <- merge(ICPMS_tidy, sample_key)

#Previewing the merged data
ICPMS_merged
```

