---
title: "ICPMS Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
```

```{r ICPMS Data}
ICPMS <- read_csv("~/R/C313_JCWSoilAnalysis/Data/ICPMS_Data_Tidy.csv")
View(ICPMS)
```

```{r Defining lists}
sample_sites <- unique(filter(ICPMS, Site!="MB", Site!="")$Site)
#excluding method blank and quality control from the list of sites
metals_analyzed <- unique(ICPMS$metal)

#Preview the lists to check for potential issues
sample_sites
metals_analyzed
```

```{r Calibration}
#For loop
ICPMS_cal <- NULL
for (unique_metal in metals_analyzed){
  cal <- ICPMS %>%
    filter(Type== "Cal1" | Type== "Cal2" | Type== "Cal3") %>%
    filter(metal == unique_metal)%>%
    select(Concentration,CPS,RSD)
  
#Perform a weighted linear regression, account for uncertainty in the CPS by weighting the regression with the RSD readings  
  w <- 1/(cal$CPS*cal$RSD)^2
  model <- lm(cal$CPS ~ cal$Concentration, weights = w)
  
#Pulling info from model to be stored in a tidy calibration data set  
  slope <- model$coefficients[2]
  intercept <- model$coefficients[1]
  slope_std <- summary(model)$coefficients[2,2]
  intercept_std <- summary(model)$coefficients[1,2]
 
#Plot calibration curve   
  plot(cal$CPS ~ cal$Concentration,
       xlab= paste("Concentration of ", unique_metal, "(ppb)"), #units from the standard solution prepared at OHSU (µg/L)
       ylab= "Counts per second")+
       abline(model, col="red")+
       title(paste("Calibration for", unique_metal))
  equation <- tibble(metal= unique_metal, slope, slope_std, intercept, intercept_std)
  ICPMS_cal <- rbind(ICPMS_cal, equation)
}

ICPMS_cal
#Clearing the envrironment
remove(equation, cal, slope, slope_std, intercept, intercept_std, w, model, unique_metal)
```

```{r Creating a function for sample analysis}
#inputs: unique_site (as a character, ex. "A")
#outputs: concentration vector

sample_analysis <- function(unique_Site){
  concentration_data <- NULL
  for (unique_metal in metals_analyzed){
    sample <- filter(ICPMS, metal == unique_metal, site == unique_site)
    data <- NULL
    
    for(ID in sample$sample_key){
      sample_data <- filter(sample, sample_key == ID)
      cal <- filter(ICPMS_cal, metal == unique_metal)
      
      #sample analysis
      m <- cal$slope
      b <- cal$intercept
      y <- sample_data$cps
      
      b_e <- cal$intercept_std
      m_e <- cal$slope_std
      
      x <- (y-b)/m #The units are dependent on the calibration standards (Kg/mL)
      
      rsd <- sample_data$RSD
      cps <- sample_data$CPS
      
      #error propagation
      e_yb <- sqrt((rsd)^2 + (b_e)^2) 
      #error in the y-b from the calibration
      yb <- cps-b
      e_x <- x*sqrt((e_yb/yb)^2 + (m_e/m)^2)
      #error in x from the calibration
      
      data <- rbind(data, data_frame(sample_key = ID, x, e_x))
      if(unique_site != "MB"){
        concentration_data <- data_frame(sample_key = sample_data$sample_key,
                                         analyst = sample_data$analyst,
                                         metal = unique_metal,
                                         Site = unique_site,
                                         conc_dil = x,
                                         conc_dil_error = e_x)%>%
          rbind(concentration_data)
      }
      if (unique_site=="MB"){
        x <- mean(data$x)
        e_x <- sd(data$x)
        concentration_data <- data_frame(metal = unique_metal,
                                         Site = unique_Site,
                                         conc_dil = x,
                                         conc_dil_error = e_x) %>%
          rbind(concentration_data)
      }
    }
    return(concentration_data)
  }
}
```

