---
title: "AA Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(janitor)
```

1) Importing the Data
```{r, warning=FALSE, message=TRUE}
#Import AA data -> find path by right clicking on data file -> import dataset. Change the first column to "number", the second column to "double", and the third to "number". Change the skip to 4. Copy the path at the top, add it to the code in the bottom right zone. Copy the code and run it in this chunk.

AA_Data <- read_csv("~/R/C313_JCWSoilAnalysis/Data/AA_Data.csv", col_types = cols(`%RSD` = col_number(), 
    Analysis = col_number(), `Mean Abs.` = col_double(), 
    `Sample Key` = col_number(), X2 = col_double(), 
    X3 = col_number()), skip = 4)
View(AA_Data)

sample_key <- read_csv("~/R/C313_JCWSoilAnalysis/Data/Sample_Key.csv")

#Preview Data
AA_Data
sample_key
```

2) Merging the Sample Key
```{r merging sample key}
#Merging together the AA Data and the Sample Key
AA_merged <- merge(AA_Data, sample_key)

#Previewing the merged data
AA_merged

```
