---
title: "AA_test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(janitor)
```

1) Importing the Data
```{r, warning=FALSE, message=TRUE}
#Import AA data -> find path by right clicking on data file (already uploaded in R and selecting "import dataset")
AA_Data <- read.csv("~/R/C313_JCWSoilAnalysis/Data/AA_Data.csv", skip=4, na="N/A") 

#Import sample key data -> find path by right clicking on data file (already uploaded in R and selecting "import dataset")
sample_key <- read.csv("~/R/C313_JCWSoilAnalysis/Data/Sample_Key.csv", skip=0)

#Preview Data
AA_Data
sample_key
```

```{r mutating the Sample Key}
sample_key_tidy <- sample_key %>%
  mutate(Sample.Key = as.character(Sample.Key))

#Preview data sets
view(sample_key_tidy)
view(AA_Data)
```

```{r fully joining datasets}
#new joined dataset formation
joined_data <- full_join(AA_Data, sample_key_tidy) 

```

```{r drop N/A's in Mean Abs.}
#Remove N/A's from Mean Abs. variable
joined_data_tidy <- joined_data %>% 
  drop_na(Mean.Abs.)

#Preview data sets
view(joined_data_tidy)
```

